<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="Jaydeeps-MBP.attlocal.net" name="com.guru99.qa.testcases.LoginPageTest" tests="4" failures="1" timestamp="18 Jul 2018 07:04:23 GMT" time="9.020" errors="0">
  <testcase name="takeScreenShotTest" time="9.020" classname="com.guru99.qa.testcases.LoginPageTest">
    <failure type="java.lang.AssertionError" message="expected [Guru9009 Bank Home Page] but found [Guru99 Bank Home Page]">
      <![CDATA[java.lang.AssertionError: expected [Guru9009 Bank Home Page] but found [Guru99 Bank Home Page]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:137)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:453)at org.testng.Assert.assertEquals(Assert.java:463)at com.guru99.qa.testcases.LoginPageTest.takeScreenShotTest(LoginPageTest.java:120)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- takeScreenShotTest -->
  <testcase name="testf" classname="com.guru99.qa.testcases.LoginPageTest">
    <skipped/>
  </testcase> <!-- testf -->
  <testcase name="testShot" classname="com.guru99.qa.testcases.LoginPageTest">
    <skipped/>
  </testcase> <!-- testShot -->
  <testcase name="loginPageTitleVerificationTest" classname="com.guru99.qa.testcases.LoginPageTest">
    <skipped/>
  </testcase> <!-- loginPageTitleVerificationTest -->
</testsuite> <!-- com.guru99.qa.testcases.LoginPageTest -->
